export {default as Homepage} from './Homepage'
export {default as MortgagePage} from './MortgagePage'
export {default as ContactPage} from './ContactPage'
export {default as PropertyPage} from './PropertyPage'
export {default as AboutPage} from './AboutPage'
export {default as TourPage} from './Tourpage'